name: Build and Deploy to GitHub Pages
permissions: 
  contents: write
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          build_dir: build
          fqdn: 'find.bible'
          jekyll: false
          verbose: true
